"""Wave-03 PR-5 — operator-approval queue for cognitive proposals.

The cognitive chat graph (PR-3, PR-4) replies in natural language; if the
reply contains a structured ``propose`` block (parsed by
:mod:`intelligence_engine.cognitive.proposal_parser`) the runtime drops
the proposal into this queue. The chat reply is returned to the operator
*along with* the queued ``request_id`` (via
``ChatTurnResponse.proposal_id``) so the client can render a "pending
approval" affordance. The bus only sees a real ``SignalEvent`` after
the operator clicks **Approve** — and at that point the resulting
``SignalEvent`` is stamped with ``produced_by_engine=
"intelligence_engine.cognitive"`` (HARDEN-03) and routed through the
single execute chokepoint downstream (HARDEN-02).

Isolation contract (B1):

* This module lives under ``intelligence_engine.cognitive.*`` and may
  not import ``governance_engine.*`` or ``system_engine.*``. The HTTP
  layer (``ui.*``) wires the queue's emit-on-approve callback to the
  governance ledger and the bus.
* The queue itself is a pure, in-memory, thread-safe ledger of pending
  / decided requests. Its public surface is the four operations a
  route handler needs: ``submit``, ``decide``, ``list``, ``get``.

Determinism contract (INV-15):

* Request ids are generated by an injected ``id_factory`` (defaults to
  :func:`uuid.uuid4`). Tests pass a deterministic counter so replays
  are byte-identical.
* All timestamps are stamped by an injected ``ts_ns`` callable so the
  queue does not import :mod:`time` or
  :mod:`system_engine.time_authority` directly.
"""

from __future__ import annotations

import threading
import uuid
from collections.abc import Callable, Iterable
from dataclasses import dataclass, field

from core.contracts.api.cognitive_chat_approvals import (
    ApprovalRequestApi,
    ApprovalSideApi,
    ApprovalStatusApi,
    ProposedSignalApi,
)

__all__ = [
    "ApprovalAlreadyDecidedError",
    "ApprovalNotFoundError",
    "ApprovalQueue",
    "default_id_factory",
]


class ApprovalNotFoundError(KeyError):
    """Raised when ``decide``/``get`` is given an unknown request id."""


class ApprovalAlreadyDecidedError(RuntimeError):
    """Raised when ``decide`` is called twice on the same request.

    The HTTP layer maps this to 409 Conflict — the dashboard's local
    state can briefly disagree with the server (e.g. two operator tabs)
    and the queue refuses to flip a row's status more than once."""


def default_id_factory() -> str:
    """Production id generator — uuid4 hex (32 chars)."""

    return uuid.uuid4().hex


@dataclass
class ApprovalQueue:
    """In-memory, thread-safe pending-approval ledger.

    Construction is parameterless in production
    (``ApprovalQueue()``); tests inject ``id_factory`` and ``ts_ns``
    to make the public surface deterministic.

    The queue stores fully-formed :class:`ApprovalRequestApi`
    instances — the wire shape is the canonical state. This keeps
    the route handler trivial (it just snapshots the queue) and
    forces every mutation to round-trip through the public API.
    """

    id_factory: Callable[[], str] = field(default=default_id_factory)
    ts_ns: Callable[[], int] = field(default_factory=lambda: lambda: 0)
    _rows: dict[str, ApprovalRequestApi] = field(
        default_factory=dict, init=False, repr=False
    )
    _order: list[str] = field(default_factory=list, init=False, repr=False)
    _lock: threading.Lock = field(
        default_factory=threading.Lock, init=False, repr=False, compare=False
    )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def submit(
        self,
        *,
        thread_id: str,
        proposal: ProposedSignalApi,
        requested_at_ts_ns: int | None = None,
    ) -> ApprovalRequestApi:
        """Queue a fresh ``PENDING`` row. Returns the materialised request.

        ``requested_at_ts_ns`` defaults to ``self.ts_ns()`` — pass an
        explicit value when the caller already has a TimeAuthority
        timestamp from the chat turn so the queue row matches the
        ``COGNITIVE_CHECKPOINT`` ledger row.
        """

        ts = (
            requested_at_ts_ns
            if requested_at_ts_ns is not None
            else self.ts_ns()
        )
        if proposal.side is ApprovalSideApi.HOLD:
            raise ValueError(
                "HOLD proposals must not be queued — the parser should "
                "reject them upstream"
            )

        with self._lock:
            req_id = self.id_factory()
            if req_id in self._rows:
                # Defensive guard against a buggy id_factory; the
                # production uuid4 collision probability is
                # negligible but a deterministic test factory could
                # collide if mis-seeded.
                raise RuntimeError(
                    f"approval id collision: {req_id!r}"
                )
            row = ApprovalRequestApi(
                request_id=req_id,
                thread_id=thread_id,
                requested_at_ts_ns=ts,
                proposal=proposal,
                status=ApprovalStatusApi.PENDING,
                decided_at_ts_ns=None,
                decided_by="",
            )
            self._rows[req_id] = row
            self._order.append(req_id)
            return row

    def decide(
        self,
        *,
        request_id: str,
        approved: bool,
        decided_by: str,
    ) -> ApprovalRequestApi:
        """Flip a pending row to APPROVED / REJECTED. Returns the new row.

        The transition is one-way: a second call (with the same or
        opposite verdict) raises :class:`ApprovalAlreadyDecidedError`.
        """

        with self._lock:
            row = self._rows.get(request_id)
            if row is None:
                raise ApprovalNotFoundError(request_id)
            if row.status is not ApprovalStatusApi.PENDING:
                raise ApprovalAlreadyDecidedError(
                    f"approval {request_id!r} is already "
                    f"{row.status.value}"
                )
            updated = row.model_copy(
                update={
                    "status": (
                        ApprovalStatusApi.APPROVED
                        if approved
                        else ApprovalStatusApi.REJECTED
                    ),
                    "decided_at_ts_ns": self.ts_ns(),
                    "decided_by": decided_by,
                },
            )
            self._rows[request_id] = updated
            return updated

    def get(self, request_id: str) -> ApprovalRequestApi:
        """Return the current row for ``request_id`` or raise."""

        with self._lock:
            row = self._rows.get(request_id)
            if row is None:
                raise ApprovalNotFoundError(request_id)
            return row

    def list(
        self,
        *,
        include_decided: bool = False,
    ) -> tuple[ApprovalRequestApi, ...]:
        """Snapshot the queue, oldest-first.

        Default is pending-only. ``include_decided=True`` returns the
        full audit trail for the dashboard's history panel."""

        with self._lock:
            rows: Iterable[ApprovalRequestApi] = (
                self._rows[k] for k in self._order
            )
            if not include_decided:
                rows = (
                    r for r in rows if r.status is ApprovalStatusApi.PENDING
                )
            return tuple(rows)

    def __len__(self) -> int:
        with self._lock:
            return len(self._rows)
