"""Hardening-S1 item 2 — typed governance-decision HMAC signature.

Today an :class:`~core.contracts.execution_intent.ExecutionIntent` is
content-hashed (HARDEN-01) and routed through the AuthorityGuard
chokepoint (HARDEN-02). The chain proves the *fields* were not
tampered with between Governance approval and execution -- but it
does **not** prove that *Governance* (and not some unauthorised
caller) was the party that flipped ``approved_by_governance=True``.

The architecture-review item 2 demands a cryptographic binding:

    Every governance decision must include
    ``governance_decision_id`` + ``operator_signature``;
    no signature → no execution.

This module provides the **signature primitive**:

* :class:`DecisionSigner` -- holds a per-process HMAC-SHA256 secret
  generated at process boot via :func:`secrets.token_bytes` (no
  long-lived key on disk, no key-rotation foot-gun). The secret
  never leaves the instance; the only way to produce a valid
  signature is to hold the live :class:`DecisionSigner`.

* :meth:`DecisionSigner.sign` -- compute the HMAC over the
  intent's stable identity (``content_hash`` + ``governance_decision_id``).
  ``content_hash`` already binds every contract field, so signing
  the hash is sufficient to bind the whole intent.

* :meth:`DecisionSigner.verify` -- constant-time comparison of a
  proposed signature against the recomputed HMAC.

Wiring contract
---------------

* The **GovernanceEngine** constructs **one** :class:`DecisionSigner`
  at boot and uses :meth:`sign` to bind every approved intent.

* The **AuthorityGuard** receives the *same* instance via dependency
  injection and uses :meth:`verify` at the chokepoint. Without the
  injected verifier, the guard runs in legacy (signature-not-required)
  mode for backwards compatibility -- but production wiring must pass
  the singleton so the gate is enforced.

Authority lint
--------------

* **B36** restricts construction of :class:`DecisionSigner` to
  ``governance_engine.*``. Any other module that instantiates the
  signer would hold a forged secret and could mint signatures.
  The verifier reference may be passed *anywhere* the guard runs
  (``execution_engine.*``, ``ui.*``), but the constructor is
  governance-only.

Determinism / replay
--------------------

The HMAC secret is generated by :func:`secrets.token_bytes` so
two processes produce different signatures for the same intent.
That is the *correct* shape for live runtime authority -- replay
determinism (INV-15) is provided by ``content_hash``, which is a
pure function of the contract fields. Replay tooling that must
re-derive ``content_hash`` does not need the signature; it only
needs to confirm that *some* governance signature was present at
the time, which the audit ledger records as a stable opaque
string.

T1 / pure
---------

The :meth:`sign` and :meth:`verify` methods are pure functions of
the secret + payload (no clocks, no IO, no global state). The only
side effect of this module is the one-time call to
:func:`secrets.token_bytes` inside :meth:`__init__`, which is the
session-secret bootstrap.
"""

from __future__ import annotations

import hmac
import secrets
from hashlib import sha256
from typing import Final

__all__ = [
    "DECISION_SIGNATURE_BYTE_LENGTH",
    "DecisionSigner",
    "SignatureMismatchError",
    "canonical_signing_input",
    "make_decision_signer",
]


# Length of the random session secret. 32 bytes is the canonical
# HMAC-SHA256 key size. Anything shorter would still be safe in
# practice but yields a keyspace strictly smaller than the digest
# space; anything longer is hashed down to 32 bytes by HMAC.
DECISION_SIGNATURE_BYTE_LENGTH: Final[int] = 32


class SignatureMismatchError(RuntimeError):
    """Raised when a signature fails to verify.

    The :class:`AuthorityGuard` itself raises
    :class:`UnauthorizedActorError` on guard failure, so this
    exception is reserved for callers that bypass the guard and
    explicitly call :meth:`DecisionSigner.assert_verified`.
    """


def canonical_signing_input(
    *,
    content_hash: str,
    governance_decision_id: str,
) -> bytes:
    """Build the canonical byte string the HMAC is computed over.

    The format is a fixed-width concatenation of the two stable
    identity fields with a delimiter that cannot appear inside
    either field (``content_hash`` is hex, ``governance_decision_id``
    is opaque ASCII; ``b"\\x1f"`` -- the ASCII Unit Separator -- is
    safe in both contexts).
    """

    if not isinstance(content_hash, str) or not content_hash:
        raise ValueError("content_hash must be a non-empty string")
    if not isinstance(governance_decision_id, str) or not governance_decision_id:
        raise ValueError("governance_decision_id must be a non-empty string")
    return (
        b"DIX/HMAC-SHA256/v1\x1f"
        + content_hash.encode("utf-8")
        + b"\x1f"
        + governance_decision_id.encode("utf-8")
    )


class DecisionSigner:
    """Per-process HMAC-SHA256 signer for governance decisions.

    Construct one instance at process boot and inject it into both
    the :class:`~governance_engine.engine.GovernanceEngine` (signer
    side) and the :class:`~execution_engine.execution_gate.AuthorityGuard`
    (verifier side). The secret is generated via
    :func:`secrets.token_bytes` and never leaves the instance.
    """

    name: str = "decision_signer"
    spec_id: str = "HARDENING-S1-02"

    def __init__(self, *, secret: bytes | None = None) -> None:
        if secret is None:
            secret = secrets.token_bytes(DECISION_SIGNATURE_BYTE_LENGTH)
        if not isinstance(secret, (bytes, bytearray)):
            raise TypeError("secret must be bytes")
        if len(secret) < DECISION_SIGNATURE_BYTE_LENGTH:
            raise ValueError(
                "secret must be at least "
                f"{DECISION_SIGNATURE_BYTE_LENGTH} bytes"
            )
        # ``bytes(...)`` makes a defensive copy so the caller cannot
        # mutate a passed-in ``bytearray`` after construction.
        self._secret: bytes = bytes(secret)

    def sign(
        self,
        *,
        content_hash: str,
        governance_decision_id: str,
    ) -> str:
        """Return the hex HMAC-SHA256 of the canonical signing input."""

        payload = canonical_signing_input(
            content_hash=content_hash,
            governance_decision_id=governance_decision_id,
        )
        return hmac.new(self._secret, payload, sha256).hexdigest()

    def verify(
        self,
        *,
        content_hash: str,
        governance_decision_id: str,
        signature: str,
    ) -> bool:
        """Constant-time check that ``signature`` matches.

        Returns ``False`` (instead of raising) so the call site can
        choose between hard-fail and audit-and-continue. The
        production :class:`AuthorityGuard` hard-fails on a ``False``
        return.
        """

        if not isinstance(signature, str) or not signature:
            return False
        try:
            expected = self.sign(
                content_hash=content_hash,
                governance_decision_id=governance_decision_id,
            )
        except ValueError:
            return False
        return hmac.compare_digest(expected, signature)

    def assert_verified(
        self,
        *,
        content_hash: str,
        governance_decision_id: str,
        signature: str,
    ) -> None:
        """Convenience wrapper that raises on failure.

        Used by callers that want a hard exception on a forged
        signature instead of a boolean. The :class:`AuthorityGuard`
        does not use this -- it raises ``UnauthorizedActorError``
        with structured violation context.
        """

        if not self.verify(
            content_hash=content_hash,
            governance_decision_id=governance_decision_id,
            signature=signature,
        ):
            raise SignatureMismatchError(
                "decision signature failed HMAC verification"
            )


def make_decision_signer() -> DecisionSigner:
    """Governance-owned factory for harness wiring (AUDIT-P1.1).

    The B36 authority lint rule restricts construction of
    :class:`DecisionSigner` to ``governance_engine.*`` so that only
    one HMAC secret exists per process. The harness in :mod:`ui.server`
    needs to obtain the signer it injects into the
    :class:`~execution_engine.execution_gate.AuthorityGuard` and into
    :func:`~governance_engine.harness_approver.approve_signal_for_execution`,
    but a literal ``DecisionSigner()`` call there would (correctly)
    trigger B36. This thin factory keeps the construction inside the
    governance package while exposing a single, documented entry point
    for harness boot code.
    """

    return DecisionSigner()
