"""
mind.knowledge.seed_traders \u2014 curated worldwide trader roster.

Historical \u2192 present, all regions. Each entry: name, era, region, style,
strategy tags, 1-line philosophy, signature trade, canonical source,
cautionary flag. Designed to grow organically via ingestion.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SeedTrader:
    name: str
    era: str
    region: str
    style: str                              # classical/value/macro/quant/crypto/...
    strategies: tuple[str, ...] = ()
    philosophy: str = ""
    signature: str = ""
    source: str = ""
    cautionary: bool = False


_SEED: tuple[SeedTrader, ...] = (
    # Classical / pre-war
    SeedTrader("Charles Dow", "1880s-1900s", "US", "classical", ("dow_theory",),
               "The market reflects all known information in its price.",
               "Founded Dow Jones; formalized trend theory.",
               "https://en.wikipedia.org/wiki/Charles_Dow"),
    SeedTrader("Richard D. Wyckoff", "1910s-1930s", "US", "classical",
               ("wyckoff_method", "accumulation_distribution"),
               "Follow the composite operator.",
               "Codified tape reading + supply/demand phases.",
               "https://en.wikipedia.org/wiki/Richard_Wyckoff"),
    SeedTrader("Jesse Livermore", "1900s-1940s", "US", "classical",
               ("trend_following", "pivot_points"),
               "The big money is made in the sitting.",
               "Shorted 1907 + 1929 crashes.",
               "https://en.wikipedia.org/wiki/Jesse_Lauriston_Livermore", True),
    SeedTrader("W.D. Gann", "1900s-1950s", "US", "classical",
               ("gann_angles", "cycles", "time_price_squared"),
               "Time is more important than price.",
               "Geometric/astro price-time analysis.",
               "https://en.wikipedia.org/wiki/William_Delbert_Gann"),
    SeedTrader("Ralph Elliott", "1930s-1940s", "US", "classical",
               ("elliott_wave",),
               "Market moves in 5-wave impulse + 3-wave correction.",
               "Wave Principle (1938).",
               "https://en.wikipedia.org/wiki/Ralph_Nelson_Elliott"),
    SeedTrader("Richard Schabacker", "1920s-1930s", "US", "classical",
               ("chart_patterns",),
               "Charts capture the collective mind of the market.",
               "Founder of technical analysis as a discipline.",
               "https://en.wikipedia.org/wiki/Richard_W._Schabacker"),
    SeedTrader("Bernard Baruch", "1900s-1960s", "US", "classical",
               ("trend_following",),
               "Don't try to buy at the bottom and sell at the top.",
               "Shorted 1929 crash; advised presidents.",
               "https://en.wikipedia.org/wiki/Bernard_Baruch"),
    SeedTrader("John Maynard Keynes", "1920s-1940s", "UK", "classical",
               ("contrarian", "macro"),
               "Markets can stay irrational longer than you can stay solvent.",
               "Managed Kings College endowment.",
               "https://en.wikipedia.org/wiki/John_Maynard_Keynes"),
    # Value
    SeedTrader("Benjamin Graham", "1930s-1970s", "US", "value",
               ("margin_of_safety", "net-net", "deep_value"),
               "In the short run the market is a voting machine; in the long run it's a weighing machine.",
               "The Intelligent Investor; Security Analysis.",
               "https://en.wikipedia.org/wiki/Benjamin_Graham"),
    SeedTrader("Warren Buffett", "1960s-present", "US", "value",
               ("moat", "compounding", "concentration"),
               "Be fearful when others are greedy.",
               "Berkshire Hathaway; Coca-Cola; American Express.",
               "https://en.wikipedia.org/wiki/Warren_Buffett"),
    SeedTrader("Charlie Munger", "1960s-2020s", "US", "value",
               ("mental_models", "latticework"),
               "Invert, always invert.",
               "BRK vice chairman.",
               "https://en.wikipedia.org/wiki/Charlie_Munger"),
    SeedTrader("Philip Fisher", "1930s-1990s", "US", "value",
               ("growth", "scuttlebutt"),
               "Common Stocks and Uncommon Profits.",
               "Held Motorola for decades.",
               "https://en.wikipedia.org/wiki/Philip_Fisher"),
    SeedTrader("John Templeton", "1940s-2000s", "US/Bahamas", "value",
               ("global_value", "contrarian"),
               "Buy at the point of maximum pessimism.",
               "Templeton Growth Fund global expansion.",
               "https://en.wikipedia.org/wiki/John_Templeton"),
    SeedTrader("Peter Lynch", "1970s-1990s", "US", "value",
               ("growth_at_reasonable_price", "buy_what_you_know"),
               "Know what you own and know why you own it.",
               "Magellan Fund 13-year 29% CAGR.",
               "https://en.wikipedia.org/wiki/Peter_Lynch"),
    SeedTrader("Walter Schloss", "1950s-2000s", "US", "value",
               ("deep_value", "graham_disciple"),
               "Low P/B, low debt, patience.",
               "WJS Partners 45 years at ~15%.",
               "https://en.wikipedia.org/wiki/Walter_Schloss"),
    SeedTrader("Seth Klarman", "1980s-present", "US", "value",
               ("margin_of_safety", "distressed"),
               "Risk is a permanent loss of capital.",
               "Baupost Group.",
               "https://en.wikipedia.org/wiki/Seth_Klarman"),
    SeedTrader("Joel Greenblatt", "1980s-present", "US", "value",
               ("magic_formula", "spinoffs", "special_situations"),
               "Buy good companies cheap.",
               "Gotham Capital 40% CAGR 10yrs.",
               "https://en.wikipedia.org/wiki/Joel_Greenblatt"),
    SeedTrader("Mohnish Pabrai", "1990s-present", "US/India", "value",
               ("cloning", "concentrated"),
               "Heads I win, tails I don't lose much.",
               "Pabrai Investment Funds.",
               "https://en.wikipedia.org/wiki/Mohnish_Pabrai"),
    SeedTrader("Francisco García Paramés", "1990s-present", "Spain", "value",
               ("global_value",),
               "The Spanish Warren Buffett.",
               "Bestinver, later Cobas AM.",
               "https://en.wikipedia.org/wiki/Francisco_Garc%C3%ADa_Param%C3%A9s"),
    # Macro
    SeedTrader("George Soros", "1970s-present", "Hungary/US", "macro",
               ("reflexivity", "global_macro"),
               "It's not whether you're right or wrong, but how much you make when right.",
               "Broke the Bank of England (1992 GBP short).",
               "https://en.wikipedia.org/wiki/George_Soros"),
    SeedTrader("Stanley Druckenmiller", "1980s-present", "US", "macro",
               ("global_macro", "concentration"),
               "The way to build long-term returns is through preservation of capital and home runs.",
               "GBP 1992 trade with Soros; Nasdaq 1999.",
               "https://en.wikipedia.org/wiki/Stanley_Druckenmiller"),
    SeedTrader("Paul Tudor Jones", "1980s-present", "US", "macro",
               ("trend", "risk_management"),
               "Losers average losers.",
               "Predicted 1987 crash; Tudor Investment Corp.",
               "https://en.wikipedia.org/wiki/Paul_Tudor_Jones"),
    SeedTrader("Louis Bacon", "1980s-2020s", "US", "macro",
               ("global_macro",),
               "Macro requires global curiosity.",
               "Moore Capital Management.",
               "https://en.wikipedia.org/wiki/Louis_Bacon"),
    SeedTrader("Ray Dalio", "1970s-present", "US", "macro",
               ("all_weather", "risk_parity", "principles"),
               "Pain + reflection = progress.",
               "Bridgewater Pure Alpha + All Weather.",
               "https://en.wikipedia.org/wiki/Ray_Dalio"),
    SeedTrader("Julian Robertson", "1980s-2000s", "US", "macro",
               ("long_short_equity", "tiger_cubs"),
               "Hire smart people and trust them.",
               "Tiger Management founder; legendary analyst tree.",
               "https://en.wikipedia.org/wiki/Julian_Robertson"),
    SeedTrader("Michael Steinhardt", "1960s-1990s", "US", "macro",
               ("variant_perception",),
               "Variant perception pays.",
               "Steinhardt Partners 24%/yr 28 yrs.",
               "https://en.wikipedia.org/wiki/Michael_Steinhardt"),
    SeedTrader("Bruce Kovner", "1970s-2010s", "US", "macro",
               ("global_macro", "commodities"),
               "If you diversify, control risk, ride trends, you make money.",
               "Caxton Associates 21%/yr.",
               "https://en.wikipedia.org/wiki/Bruce_Kovner"),
    # Quant
    SeedTrader("Edward Thorp", "1960s-present", "US", "quant",
               ("card_counting", "kelly", "statistical_arb"),
               "Edge + Kelly bet size = wealth.",
               "Beat the Dealer, Beat the Market; PNP.",
               "https://en.wikipedia.org/wiki/Edward_O._Thorp"),
    SeedTrader("Jim Simons", "1970s-2020s", "US", "quant",
               ("signal_hunting", "pattern_recognition"),
               "Machines don't panic.",
               "Renaissance Medallion 66% gross/yr.",
               "https://en.wikipedia.org/wiki/Jim_Simons_(mathematician)"),
    SeedTrader("David E. Shaw", "1980s-present", "US", "quant",
               ("statistical_arb", "high_perf_computing"),
               "Math + compute + discipline.",
               "D.E. Shaw & Co.",
               "https://en.wikipedia.org/wiki/David_E._Shaw"),
    SeedTrader("Peter Muller", "1990s-present", "US", "quant",
               ("equity_quant",),
               "PDT / Morgan Stanley market neutral.",
               "PDT Partners.",
               "https://en.wikipedia.org/wiki/Peter_Muller_(trader)"),
    SeedTrader("Nunzio Tartaglia", "1980s", "US", "quant",
               ("pairs_trading", "stat_arb"),
               "Systematic pairs revolution at Morgan Stanley.",
               "APT group Morgan Stanley.",
               "https://en.wikipedia.org/wiki/Pairs_trade"),
    SeedTrader("Benoit Mandelbrot", "1960s-2000s", "France/US", "quant",
               ("fractal_markets", "fat_tails"),
               "Markets are wilder than Gaussian.",
               "(Mis)Behavior of Markets.",
               "https://en.wikipedia.org/wiki/Benoit_Mandelbrot"),
    SeedTrader("Emanuel Derman", "1980s-2010s", "South Africa/US", "quant",
               ("derivatives", "local_vol"),
               "Models are myth; models are useful.",
               "Goldman Sachs quant; My Life as a Quant.",
               "https://en.wikipedia.org/wiki/Emanuel_Derman"),
    SeedTrader("Marcos Lopez de Prado", "2000s-present", "Spain/US", "quant",
               ("ml_finance", "meta_labeling"),
               "Advances in Financial ML.",
               "AQR, True Positive Technologies.",
               "https://en.wikipedia.org/wiki/Marcos_Lopez_de_Prado"),
    SeedTrader("Cliff Asness", "1990s-present", "US", "quant",
               ("value_momentum", "factors"),
               "Factors work, but not always.",
               "AQR Capital.",
               "https://en.wikipedia.org/wiki/Clifford_Asness"),
    # Hedge-fund modern
    SeedTrader("Kenneth Griffin", "1990s-present", "US", "hedge_fund",
               ("multi_strategy",),
               "Citadel cross-asset multi-pod.",
               "Citadel / Citadel Securities.",
               "https://en.wikipedia.org/wiki/Ken_Griffin_(businessman)"),
    SeedTrader("Steven Cohen", "1990s-present", "US", "hedge_fund",
               ("fundamental_long_short",),
               "Stamina of a sprinter daily.",
               "SAC / Point72.",
               "https://en.wikipedia.org/wiki/Steven_A._Cohen"),
    SeedTrader("Bill Ackman", "1990s-present", "US", "hedge_fund",
               ("activist", "concentrated_long_short"),
               "Activist catalysts unlock value.",
               "Pershing Square; GGP; Herbalife short.",
               "https://en.wikipedia.org/wiki/Bill_Ackman"),
    SeedTrader("David Einhorn", "1990s-present", "US", "hedge_fund",
               ("short_selling", "accounting_skeptic"),
               "Fooling Some of the People.",
               "Greenlight Capital; Lehman short.",
               "https://en.wikipedia.org/wiki/David_Einhorn"),
    SeedTrader("Dan Loeb", "1990s-present", "US", "hedge_fund",
               ("activist",),
               "Third Point poison-pen letters.",
               "Third Point Capital.",
               "https://en.wikipedia.org/wiki/Daniel_S._Loeb"),
    SeedTrader("John Paulson", "2000s-present", "US", "hedge_fund",
               ("event_driven", "subprime_short"),
               "Biggest trade in history vs subprime 2007.",
               "Paulson & Co.",
               "https://en.wikipedia.org/wiki/John_Paulson"),
    SeedTrader("Michael Burry", "2000s-present", "US", "hedge_fund",
               ("contrarian", "deep_value", "big_short"),
               "Obsession beats IQ.",
               "Scion Capital; subprime CDS 2005-07.",
               "https://en.wikipedia.org/wiki/Michael_Burry"),
    SeedTrader("Carl Icahn", "1970s-present", "US", "hedge_fund",
               ("corporate_raider", "activist"),
               "Put companies in play.",
               "TWA; Netflix; Apple stakes.",
               "https://en.wikipedia.org/wiki/Carl_Icahn"),
    SeedTrader("Cathie Wood", "2010s-present", "US", "hedge_fund",
               ("disruptive_innovation", "thematic"),
               "Bet on innovation S-curves.",
               "ARK Invest ARKK.",
               "https://en.wikipedia.org/wiki/Cathie_Wood"),
    SeedTrader("Paul Marshall", "2000s-present", "UK", "hedge_fund",
               ("long_short_equity",),
               "Marshall Wace TOPS signal-harvesting.",
               "Marshall Wace.",
               "https://en.wikipedia.org/wiki/Marshall_Wace"),
    # Asia / non-Western
    SeedTrader("Hiroshi Mikitani", "1990s-present", "Japan", "entrepreneur_investor",
               ("internet",), "Japan's e-commerce builder.",
               "Rakuten founder.",
               "https://en.wikipedia.org/wiki/Hiroshi_Mikitani"),
    SeedTrader("Masayoshi Son", "1980s-present", "Japan", "vc_trader",
               ("venture", "concentrated_bets"),
               "300-year plan; Vision Fund.",
               "Alibaba pre-IPO 20x; Uber; ARM.",
               "https://en.wikipedia.org/wiki/Masayoshi_Son"),
    SeedTrader("Li Ka-Shing", "1950s-2010s", "Hong Kong", "value",
               ("conglomerate",),
               "Buy low, sell high, diversify.",
               "CK Hutchison; global ports.",
               "https://en.wikipedia.org/wiki/Li_Ka-shing"),
    SeedTrader("Rakesh Jhunjhunwala", "1980s-2020s", "India", "value",
               ("contrarian", "long_term_india"),
               "India's Warren Buffett.",
               "Titan Company 10,000x.",
               "https://en.wikipedia.org/wiki/Rakesh_Jhunjhunwala"),
    SeedTrader("Radhakishan Damani", "1980s-present", "India", "value",
               ("concentrated",),
               "Quiet conviction.",
               "DMart; founded Damani Finance.",
               "https://en.wikipedia.org/wiki/Radhakishan_Damani"),
    SeedTrader("Uday Kotak", "1980s-present", "India", "value",
               ("banking",),
               "Trust + discipline.",
               "Kotak Mahindra Bank founder.",
               "https://en.wikipedia.org/wiki/Uday_Kotak"),
    SeedTrader("Wang Yawei", "1990s-present", "China", "hedge_fund",
               ("china_a_shares",),
               "Top-ranked China fund manager.",
               "China Asset Management.",
               "https://en.wikipedia.org/wiki/Wang_Yawei"),
    SeedTrader("But Ka-Wai", "1990s-present", "Hong Kong", "hedge_fund",
               ("asia_macro",), "Value Partners.", "Value Partners Group.",
               "https://en.wikipedia.org/wiki/Value_Partners_Group"),
    SeedTrader("Hugh Young", "1980s-present", "UK/Singapore", "value",
               ("asia_equity",),
               "Long-term Asia fundamental.",
               "Aberdeen Standard Asia.",
               "https://en.wikipedia.org/wiki/Hugh_Young"),
    SeedTrader("Teruhide Sato", "2000s-present", "Japan", "vc_trader",
               ("emerging_tech",),
               "Netprice / Beenos / BeeNext.",
               "BeeNext founder.",
               "https://en.wikipedia.org/wiki/Teruhide_Sato"),
    # Floor / pit era
    SeedTrader("Joe Ritchie", "1980s-2000s", "US", "floor",
               ("options_mm",),
               "Market making requires humility.",
               "CRT (Chicago Research & Trading).",
               "https://en.wikipedia.org/wiki/Joseph_Ritchie"),
    SeedTrader("Mark Ritchie", "1980s-2000s", "US", "floor",
               ("commodities",),
               "God in the Pits.",
               "CRT co-founder.",
               "https://www.goodreads.com/book/show/1062559.God_in_the_Pits"),
    SeedTrader("Blair Hull", "1980s-2000s", "US", "floor",
               ("options", "volatility"),
               "Systematic options market making.",
               "Hull Trading Company.",
               "https://en.wikipedia.org/wiki/Blair_Hull"),
    SeedTrader("Linda Raschke", "1980s-present", "US", "floor",
               ("short_term_momentum",),
               "Street Smarts.",
               "LBRGroup.",
               "https://en.wikipedia.org/wiki/Linda_Raschke"),
    SeedTrader("Tony Saliba", "1980s-2000s", "US", "floor",
               ("options", "volatility_skew"),
               "100K/month options.",
               "LETCO founder.",
               "https://en.wikipedia.org/wiki/Tony_Saliba"),
    SeedTrader("Mark Cook", "1980s-2000s", "US", "floor",
               ("options",),
               "Cook Cumulative Tick indicator.",
               "US Investing Championship winner.",
               "https://en.wikipedia.org/wiki/Mark_Cook"),
    # Market Wizards alumni (additional)
    SeedTrader("Ed Seykota", "1970s-2010s", "US", "quant",
               ("trend_following", "systems"),
               "Everybody gets what they want from the market.",
               "Pioneer computerized trend systems.",
               "https://en.wikipedia.org/wiki/Ed_Seykota"),
    SeedTrader("Richard Dennis", "1970s-1990s", "US", "trend",
               ("turtle", "trend_following"),
               "Traders can be taught.",
               "Turtle Traders experiment.",
               "https://en.wikipedia.org/wiki/Richard_Dennis"),
    SeedTrader("William Eckhardt", "1970s-2010s", "US", "trend",
               ("turtle", "systematic"),
               "Avoid risk-of-ruin above all.",
               "Co-designed Turtle system.",
               "https://en.wikipedia.org/wiki/William_Eckhardt"),
    SeedTrader("Larry Hite", "1980s-present", "US", "trend",
               ("trend_following", "risk_first"),
               "The Rule.",
               "Mint Investment Management.",
               "https://en.wikipedia.org/wiki/Larry_Hite"),
    SeedTrader("Marty Schwartz", "1970s-2000s", "US", "day_trade",
               ("momentum", "indicators"),
               "Pit Bull.",
               "US Investing Championship.",
               "https://en.wikipedia.org/wiki/Martin_Schwartz"),
    SeedTrader("Mark Minervini", "1990s-present", "US", "momentum",
               ("sepa", "growth_momentum"),
               "Trade Like a Stock Market Wizard.",
               "US Investing Championship 1997.",
               "https://en.wikipedia.org/wiki/Mark_Minervini"),
    # Cautionary / collapses
    SeedTrader("Long-Term Capital Mgmt (Meriwether)", "1990s", "US", "quant",
               ("fixed_income_arb",),
               "Leverage + model confidence = blowup.",
               "1998 collapse after Russia.",
               "https://en.wikipedia.org/wiki/Long-Term_Capital_Management", True),
    SeedTrader("Nick Leeson", "1990s", "UK", "rogue",
               ("derivatives",),
               "Unauthorized futures positions.",
               "Sank Barings Bank 1995.",
               "https://en.wikipedia.org/wiki/Nick_Leeson", True),
    SeedTrader("Jérôme Kerviel", "2000s", "France", "rogue",
               ("equity_derivatives",),
               "Soc Gen \u20ac4.9B loss.",
               "Record rogue trade 2008.",
               "https://en.wikipedia.org/wiki/J%C3%A9r%C3%B4me_Kerviel", True),
    SeedTrader("Bill Hwang", "2010s-2021", "Korea/US", "rogue",
               ("total_return_swaps",),
               "Concentrated CFD leverage blowup.",
               "Archegos $20B collapse 2021.",
               "https://en.wikipedia.org/wiki/Bill_Hwang", True),
    SeedTrader("Sam Bankman-Fried", "2019-2022", "US", "rogue",
               ("crypto_market_making",),
               "Alameda/FTX commingled customer funds.",
               "FTX collapse 2022.",
               "https://en.wikipedia.org/wiki/Sam_Bankman-Fried", True),
    SeedTrader("Su Zhu", "2010s-2022", "Singapore", "rogue",
               ("crypto_macro",),
               "3AC over-leveraged GBTC + Luna.",
               "Three Arrows Capital collapse 2022.",
               "https://en.wikipedia.org/wiki/Three_Arrows_Capital", True),
    SeedTrader("Do Kwon", "2018-2022", "Korea", "rogue",
               ("algorithmic_stablecoin",),
               "UST/Luna death spiral.",
               "Terra collapse May 2022.",
               "https://en.wikipedia.org/wiki/Do_Kwon", True),
    # Crypto era
    SeedTrader("Satoshi Nakamoto", "2008-2010", "pseudonymous", "crypto",
               ("first_principles",),
               "Chains of digital signatures.",
               "Bitcoin whitepaper + genesis block.",
               "https://bitcoin.org/bitcoin.pdf"),
    SeedTrader("Vitalik Buterin", "2013-present", "Russia/Canada", "crypto",
               ("protocol_design",),
               "Programmable money.",
               "Ethereum founder.",
               "https://en.wikipedia.org/wiki/Vitalik_Buterin"),
    SeedTrader("Changpeng Zhao (CZ)", "2017-present", "China/Canada", "crypto",
               ("exchange_operator",),
               "Build, then talk.",
               "Binance founder.",
               "https://en.wikipedia.org/wiki/Changpeng_Zhao"),
    SeedTrader("Arthur Hayes", "2014-present", "US/HK", "crypto",
               ("derivatives",),
               "BitMEX perp swap invention.",
               "BitMEX founder.",
               "https://en.wikipedia.org/wiki/Arthur_Hayes"),
    SeedTrader("Hayden Adams", "2018-present", "US", "crypto",
               ("amm",),
               "Constant-product AMM for all.",
               "Uniswap founder.",
               "https://en.wikipedia.org/wiki/Uniswap"),
    SeedTrader("Michael Saylor", "2020-present", "US", "crypto",
               ("treasury_btc",),
               "Bitcoin is digital property.",
               "MicroStrategy corporate BTC buyer.",
               "https://en.wikipedia.org/wiki/Michael_Saylor"),
    SeedTrader("Barry Silbert", "2010s-present", "US", "crypto",
               ("venture", "otc"),
               "DCG / Grayscale architect.",
               "GBTC pioneer.",
               "https://en.wikipedia.org/wiki/Barry_Silbert"),
    SeedTrader("Pantera Capital (Dan Morehead)", "2013-present", "US", "crypto",
               ("long_term_btc",),
               "Bitcoin as base case.",
               "Pantera Bitcoin Fund.",
               "https://en.wikipedia.org/wiki/Pantera_Capital"),
    # Retail legends / educators
    SeedTrader("Ross Cameron", "2010s-present", "US", "day_trade",
               ("small_cap_momentum",),
               "Small-cap gap-and-go.",
               "Warrior Trading.",
               "https://www.warriortrading.com/"),
    SeedTrader("Andrew Aziz", "2010s-present", "Canada", "day_trade",
               ("opening_range",),
               "How to Day Trade for a Living.",
               "Bear Bull Traders.",
               "https://bearbulltraders.com/"),
    SeedTrader("Tim Sykes", "2000s-present", "US", "day_trade",
               ("penny_stock_short",),
               "Pump-and-dump shorts.",
               "Profitly trainer.",
               "https://en.wikipedia.org/wiki/Timothy_Sykes"),
)


def all_seeds() -> tuple[SeedTrader, ...]:
    return _SEED


def seed_into(kb) -> int:
    """Upsert all seeds into a TraderKnowledge instance. Returns count."""
    n = 0
    for t in _SEED:
        trader_id = kb.upsert_trader(
            t.name,
            era=t.era, region=t.region,
            style_tags=",".join([t.style, *t.strategies]),
            cautionary=1 if t.cautionary else 0,
            bio_summary=t.philosophy,
            bio_lang="en",
            source_url=t.source,
        )
        if t.signature:
            try:
                kb.add_statement(
                    trader_id=trader_id,
                    kind="signature",
                    text=t.signature,
                    lang="en",
                    source_url=t.source,
                )
            except Exception:
                pass
        n += 1
    return n


__all__ = ["SeedTrader", "all_seeds", "seed_into"]
